using Azure.Identity;
using Microsoft.Graph;
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;

namespace AppRegistrationClassLibrary
{
    public class AppRegistrationCredentialsManager
    {
        private readonly AppRegistrationAccessTokenService appRegistrationAccessTokenService;
        private readonly IOptionsMonitor<AppRegistrationCredentialsManagerConfiguration> appRegistrationCredentialsManagerConfiguration;
        private GraphServiceClient? graphServiceClient;

        public AppRegistrationCredentialsManager(AppRegistrationAccessTokenService appRegistrationAccessTokenService, IOptionsMonitor<AppRegistrationCredentialsManagerConfiguration> appRegistrationCredentialsManagerConfiguration)
        {
            this.appRegistrationAccessTokenService = appRegistrationAccessTokenService;
            this.appRegistrationCredentialsManagerConfiguration = appRegistrationCredentialsManagerConfiguration;
            CreateTimer();
        }

        private void CreateTimer()
        {
            var timer = new PeriodicTimer(
                TimeSpan.FromTicks(appRegistrationCredentialsManagerConfiguration.CurrentValue.RefreshCycle));

            Task.Run(async () =>
                {
                    while (await timer.WaitForNextTickAsync())
                    {
                        //Business logic
                    }
                }
            );
        }
        public GraphServiceClient BuildGraphServiceClientAsync()
        {
            var scopes = new[] { "https://graph.microsoft.com/.default" };

            var tokenCredential = appRegistrationAccessTokenService.ClientCertificateCredentialFactory();

            var graphClient = new GraphServiceClient(tokenCredential, scopes);
            return graphClient;
        }

        public GraphServiceClient GraphServiceClient
        {
            get
            {
                if (graphServiceClient is not Microsoft.Graph.GraphServiceClient)
                {
                    graphServiceClient = BuildGraphServiceClientAsync();
                }
                return graphServiceClient;
            }
        }
        public async Task<IEnumerable<Application>> GetAppRegistration(CancellationToken cancellationToken = default)
        {
            var applicationCollection = await GraphServiceClient.Applications.Request().GetAsync();
            var applications = new List<Application>();

            var applicationFunc = (Application app) =>
            {
                if (app.AppId == appRegistrationAccessTokenService.AppRegistrationConfiguration.ClientId)
                {
                    applications.Add(app);
                }
                return !cancellationToken.IsCancellationRequested;
            };

            var pageIterator = PageIterator<Application>.CreatePageIterator(graphServiceClient, applicationCollection, applicationFunc);

            await pageIterator.IterateAsync();
            return applications;

        }
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Requires Permission https://graph.microsoft.com/Application.ReadWrite.OwnedBy
        /// </remarks>
        /// <param name="application"></param>
        /// <returns></returns>
        public async Task AddSecretAsync(Application application)
        {
            var passwordCredential = new PasswordCredential
            {
                DisplayName = $"Auto. generated by {Assembly.GetExecutingAssembly()}",
                StartDateTime = DateTime.Now,
                EndDateTime = DateTime.Now.AddMinutes(3),
                Hint = "some hints",
            };
            
            var appCollection = GraphServiceClient.Applications[application.Id];
            var passwordRequestBuilder = appCollection.AddPassword(passwordCredential);
            var ok = await passwordRequestBuilder.Request().PostAsync();
        }

        public async Task RemoveSecrectAsync(Application application, Guid secrectGuid)
        {
            var appCollection = GraphServiceClient.Applications[application.Id];
            var passwordRemoveBuilder = appCollection.RemovePassword(secrectGuid);
            var ok = await passwordRemoveBuilder.Request().PostResponseAsync();
        }
        public async Task AddCertificate(Application application)
        {
            var passwordCredential = new PasswordCredential
            {
                DisplayName = "Password friendly name",
                StartDateTime = DateTime.Now,
                EndDateTime = DateTime.Now.AddMinutes(3),
                Hint = "some hints",
            };


            var appCollection = GraphServiceClient.Applications[application.Id];
            var passwordRequestBuilder = appCollection.AddPassword(passwordCredential);

            var ok = await passwordRequestBuilder.Request().PostResponseAsync();

        }

    }
}
